### PR TITLE
Find pets + Schedule Meetup

### PR DESCRIPTION
**Pull request by mub2332**
- Changed home page to Find Pets page
- Updated some imports in package.json
- Async issue: the pets don't load at the start and you have to either toggle the sidebar a couple of times or go change from desktop to mobile view in Chrome (or vice versa)

Other than that, the functionality works as expected.

### CODE REVIEW

**Comment by riordanalfredo** [comment]
Have you tested it?

**Comment by mub2332** [comment]
Yeah, it works on iOS and should work on Android too

**Comment by riordanalfredo** [comment]
Great! Anyway, could you please pull request from Master branch first, resolve conflicts, and then push it again? Thanks!

**Comment by mub2332** [comment]
Ok done

**Comment by riordanalfredo** [comment]
Great! It should be stable now.

**Pull request merged**
