### PR TITLE
SMS Demo

### PR DESCRIPTION
**Pull request by mub2332**
At the moment contains two input fields for phone number and text message.
It opens up the iMessage app on iOS with the text field pre-filled with the message input in the app.

### CODE REVIEW

**Comment by riordanalfredo** [comment]
Have you tried to merge it with the Master branch (with Contact page in it)? Because I didn't see it in this branch history 😄 .

**Comment by mub2332** [comment]
Yeah I merged with master after the Contacts branch had been merged into it. It shows up when you view the branch itself but not on the PR

**Comment by riordanalfredo** [comment]
@mub2332 I fixed the issue in Android by adding this
image
In the AndroidManifest.xml. 
However, it seems that I could not send any messages into my own phone number. I don't know if that SMS actually works in IOS devices. Please let me know 👍

**Comment by mub2332** [comment]
Can confirm that the message goes through in iOS. It seems like you have to do a little more leg work for Android by implementing two functions to check and request SMS permissions. I'll take a look at it tomorrow.

**Pull request merged**
